/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;
import java.sql.*;
import businessLayer.CSDL;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author Vu Khanh
 */
public class Frm_Login extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Login
     */
    public Frm_Login() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(255,255,255,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Txt_UserName = new javax.swing.JTextField();
        Txt_Password = new javax.swing.JTextField();
        chk_remeberme = new javax.swing.JCheckBox();
        Btn_DangNhap = new javax.swing.JButton();
        Btn_Dong = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng Nhập");
        setBackground(new java.awt.Color(255, 255, 255));
        setName("Frm_Login"); // NOI18N
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 153, 255));
        jLabel1.setText("ĐĂNG NHẬP");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 153, 255));
        jLabel2.setText("Tên tài khoản:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 153, 255));
        jLabel3.setText("Mật khẩu:");

        Txt_UserName.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        Txt_UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_UserNameActionPerformed(evt);
            }
        });

        Txt_Password.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        chk_remeberme.setBackground(new java.awt.Color(255, 255, 255));
        chk_remeberme.setText("Nhớ mật khẩu");
        chk_remeberme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_remebermeActionPerformed(evt);
            }
        });

        Btn_DangNhap.setBackground(new java.awt.Color(102, 102, 255));
        Btn_DangNhap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Btn_DangNhap.setForeground(new java.awt.Color(255, 255, 255));
        Btn_DangNhap.setText("Đăng Nhập");
        Btn_DangNhap.setBorder(null);
        Btn_DangNhap.setBorderPainted(false);
        Btn_DangNhap.setPreferredSize(new java.awt.Dimension(103, 35));
        Btn_DangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DangNhapActionPerformed(evt);
            }
        });

        Btn_Dong.setBackground(new java.awt.Color(204, 204, 204));
        Btn_Dong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Btn_Dong.setText("Đóng");
        Btn_Dong.setBorder(null);
        Btn_Dong.setBorderPainted(false);
        Btn_Dong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DongActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-286.png"))); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(245, 245));
        jLabel4.setMinimumSize(new java.awt.Dimension(245, 245));
        jLabel4.setPreferredSize(new java.awt.Dimension(245, 245));
        jLabel4.setVerifyInputWhenFocusTarget(false);

        jLabel4.setPreferredSize(new Dimension(245, 245));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Txt_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Txt_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chk_remeberme, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addComponent(Btn_DangNhap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Btn_Dong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(63, 63, 63))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Txt_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Txt_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chk_remeberme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_DangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Dong, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Txt_UserName.setBorder(BorderFactory.createMatteBorder(0,0,2,0, Color.BLUE));
        Txt_Password.setBorder(BorderFactory.createMatteBorder(0,0,2,0, Color.BLUE));
        Btn_DangNhap.setPreferredSize(new Dimension(107, 35));
        Btn_DangNhap.setBorderPainted(false);
        Btn_DangNhap.setBorder(new LineBorder(Color.BLACK));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_UserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_UserNameActionPerformed

    private void chk_remebermeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_remebermeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_remebermeActionPerformed

    private void Btn_DangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DangNhapActionPerformed
        // TODO add your handling code here:
        ResultSet rs;
        try(Connection ketNoi=CSDL.getKetNoi()){
        String strsql = "Select * from Users where TenTK=? and MatKhau = ?";
        PreparedStatement ps= ketNoi.prepareCall(strsql);
        ps.setString(1,Txt_UserName.getText());
        ps.setString(2,Txt_Password.getText());
        rs=ps.executeQuery();
        if(Txt_UserName.getText().equals("")){
              
            JOptionPane.showMessageDialog(this,"Chưa nhập tên tài khoản");
            Txt_UserName.requestFocusInWindow();
        }
        else if(Txt_Password.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Chưa nhập mật khẩu ");
            Txt_Password.requestFocusInWindow();
        } 
        else if(rs.next()){
            final ImageIcon icon = new ImageIcon(Frm_Login.class.getResource("/images/blue-archive.gif"));
            JOptionPane.showMessageDialog(this,"Đăng nhập thành công","Thông báo",JOptionPane.INFORMATION_MESSAGE, icon);
            QLNS qlns = new QLNS();
            qlns.setVisible(true);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(this,"Đăng nhập không thành công");
        }
    }
    catch(Exception ex){
        ex.printStackTrace();
    }
    }//GEN-LAST:event_Btn_DangNhapActionPerformed

    private void Btn_DongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DongActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_Btn_DongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_DangNhap;
    private javax.swing.JButton Btn_Dong;
    private javax.swing.JTextField Txt_Password;
    private javax.swing.JTextField Txt_UserName;
    private javax.swing.JCheckBox chk_remeberme;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
